test_strip: Fix division by zero
When no jobs have been submitted (probably due to manual
testing on the pipeline), a division by zero makes the script
fail:

  Traceback (most recent call last):
    File "../test_strip.py", line 270, in <module>
      write_test_jobs(build_result, args.output)
    File "../test_strip.py", line 198, in write_test_jobs
      test_strip.print_progress_summary()
    File "../test_strip.py", line 174, in print_progress_summary
      100
  ZeroDivisionError: division by zero

Signed-off-by: Daniel Díaz <daniel.diaz@linaro.org>