stable_email: Fix usage of elapsed_time with no replies
This fixes two problems:
  UnboundLocalError: local variable 'reply_time' referenced before assignment
because there was no reply_time, and
  AttributeError: 'NoneType' object has no attribute 'seconds'
as the elapsed time was still None, given there was no reply yet.

Signed-off-by: Daniel Díaz <daniel.diaz@linaro.org>